### ISSUE TITLE
Groovy 2.5

### ISSUE THREAD

**Issue by aaloise** [groovy/GMavenPlus#101]
Is 1.6.1 working with Groovy 2.5? Tried to use but I'm getting a lot of "cannot find symbol" and "package does not exists" when trying to compile.

**Comment by keeganwitt** [comment]
I haven't tested it yet with 2.5.  I need to rework my integration test suite to perform those tests.  I'll update this thread once I do.

**Comment by keeganwitt** [comment]
I've got the tests running now -- everything passes except GroovyDoc tests, which Daniel already reported as an issue.  What goal is failing for you? Compile?  What package and symbols is it complaining about?

**Comment by zman0900** [comment]
My build is working with groovy 2.5.0, but one thing that gave me some trouble was the groovy-all dependency. It has changed to a pom-only dependency now that just pulls in all the individual groovy modules. I had to explicitly add `<type>pom</type>` and exclude groovy-all from all other dependencies that pull it in transitively. Otherwise I got maven errors about a "missing" groovy-all jar. 

Plus this now pulls in a lot of testing related dependencies (junit, testng, etc), so having the full groovy-all in compile scope isn't ideal.

**Comment by keeganwitt** [comment]
Yep, Groovy team changed the groovy-all artifact type to pom.  I've updated the GMavenPlus examples to reflect this.

**Comment by keeganwitt** [comment]
You might consider just using groovy + whatever modules you need (like groovy-groovydoc) instead of groovy-all.  Will make your artifact smaller.  I believe groovy-all was an uberjar of all those dependencies anyway -- so now you're seeing it pull in all the stuff that was jammed into that jar.

**Comment by zman0900** [comment]
That's actually what I ended up doing, but it's a bit of a gamble since I have other dependencies that depend on older groovy-all. There's a chance one of then could be using some groovy feature that isn't in the modules I've included, and I won't discover that until runtime. I've got pretty decent unit test coverage of those parts, so it's probably fine.

**Comment by aaloise** [comment]
I'm facing exactly the same trouble with groovy-all. Since it is a pom type now, maybe that is why i'm facing errors ate compile time.

So the suggestion is to do the same that @zman0900 did? Is there an alternative way I can use groovy-all?

**Comment by keeganwitt** [comment]
If you are using something like
```xml
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy</artifactId>
    <version>2.5.0</version>
    <classifier>indy</classifier>
</dependency>
```
instead of
```xml
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.5.0</version>
    <classifier>indy</classifier>
    <type>pom</type>
</dependency>
```
Then you may be missing dependencies that provide the classes you are missing.  What class is it complaining about?

**Comment by aaloise** [comment]
For instance, it's complaining about Script, Binding and MetaMethod classes, all belonging to groovy.lang package.

The groovy.lang package is avaiable in groovy-2.5.0.jar so even if I use:

```xml
<groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy</artifactId>
    <version>2.5.0</version>
```

Or

```xml
<groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy-all</artifactId>
    <version>2.5.0</version>
    <type>pom</type>
```

Doesn't work. I can see the jar from groovy being download with the first option and the pom file with the second option. It's like is ignored or something like that.

**Comment by aaloise** [comment]
Well, don't think that is a GMavenPlus issue, so for now I'm closing this one.
